# Generated by Django 3.2.6 on 2021-11-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol_usuario',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
