# Generated by Django 3.2.6 on 2021-09-21 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id_movimiento_caja', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(max_length=1)),
                ('monto', models.BigIntegerField()),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.persona')),
            ],
        ),
        migrations.CreateModel(
            name='ComprobanteMovimiento',
            fields=[
                ('id_comprobante_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_comprobante', models.CharField(max_length=1)),
                ('id_movimiento_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cajas.movimientocaja')),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.persona')),
            ],
        ),
        migrations.CreateModel(
            name='ArqueoCaja',
            fields=[
                ('id_arqueo_caja', models.AutoField(primary_key=True, serialize=False)),
                ('monto_apertura', models.BigIntegerField()),
                ('monto_cierre', models.BigIntegerField()),
                ('fecha_apertura', models.DateField()),
                ('fecha_cierre', models.DateField()),
                ('hora_cierre', models.TimeField()),
                ('id_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cajas.caja')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.persona')),
            ],
        ),
    ]
