# Generated by Django 3.2.6 on 2021-12-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0002_delete_comprobantemovimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arqueocaja',
            name='id_caja',
        ),
        migrations.DeleteModel(
            name='Caja',
        ),
    ]
