# Generated by Django 3.2.6 on 2021-12-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0003_auto_20211202_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='monto',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='tipo_movimiento',
            field=models.CharField(choices=[('V', 'VENTA'), ('R', 'R')], max_length=1),
        ),
    ]
