# Generated by Django 3.2.6 on 2021-12-02 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0004_auto_20211202_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='hora',
            field=models.TimeField(default='13:08:51'),
        ),
        migrations.AlterField(
            model_name='arqueocaja',
            name='hora_cierre',
            field=models.TimeField(default='13:08:51'),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='tipo_movimiento',
            field=models.CharField(choices=[('V', 'V'), ('R', 'R')], max_length=1),
        ),
    ]
