# Generated by Django 3.2.6 on 2021-12-02 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cajas', '0005_auto_20211202_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arqueocaja',
            name='hora_cierre',
            field=models.TimeField(default='13:15:02'),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='hora',
            field=models.TimeField(default='13:15:02'),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
