# Generated by Django 3.2.6 on 2021-12-02 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cajas', '0006_auto_20211202_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqueocaja',
            name='monto_calculado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='monto_comprobante',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='arqueocaja',
            name='hora_cierre',
            field=models.TimeField(default='15:34:34'),
        ),
        migrations.AlterField(
            model_name='arqueocaja',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='arqueocaja',
            name='monto_apertura',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='arqueocaja',
            name='monto_cierre',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='hora',
            field=models.TimeField(default='15:34:34'),
        ),
    ]
