# Generated by Django 3.2.6 on 2021-12-02 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0007_auto_20211202_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arqueocaja',
            name='fecha_apertura',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='arqueocaja',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arqueocaja',
            name='hora_cierre',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='hora',
            field=models.TimeField(default='16:33:30'),
        ),
    ]
