# Generated by Django 3.2.6 on 2021-12-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0008_auto_20211202_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqueocaja',
            name='descripcion_comprobante',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='hora',
            field=models.TimeField(default='18:28:56'),
        ),
    ]
