# Generated by Django 3.2.6 on 2021-12-03 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0009_auto_20211202_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arqueocaja',
            name='descripcion_comprobante',
        ),
        migrations.RemoveField(
            model_name='arqueocaja',
            name='monto_comprobante',
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='hora',
            field=models.TimeField(default='01:52:20'),
        ),
        migrations.CreateModel(
            name='RetiroDineroCaja',
            fields=[
                ('id_retiro_dinero_caja', models.AutoField(primary_key=True, serialize=False)),
                ('monto_comprobante', models.PositiveIntegerField(default=0)),
                ('descripcion_comprobante', models.CharField(max_length=100, null=True)),
                ('id_arquero_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cajas.arqueocaja')),
            ],
        ),
    ]
