# Generated by Django 3.2.6 on 2021-12-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0010_auto_20211203_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='hora',
            field=models.TimeField(default='14:31:44'),
        ),
    ]
