# Generated by Django 3.2.6 on 2021-12-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0011_alter_movimientocaja_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='hora',
            field=models.TimeField(default='20:45:04'),
        ),
    ]
