# Generated by Django 3.2.6 on 2021-11-02 23:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0004_alter_persona_fecha_creacion'),
        ('articulos', '0013_auto_20211102_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('estado', models.CharField(choices=[('A', 'ACTIVO'), ('H', 'HISTORICO')], default='A', max_length=1)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('id_detalle_venta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('sub_total', models.IntegerField(default=0)),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.articulo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('estado', models.CharField(choices=[('A', 'ACTIVO'), ('H', 'HISTORICO')], default='A', max_length=1)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('hora', models.TimeField(default='23:30:15')),
                ('total', models.IntegerField(default=0)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.persona')),
                ('id_detalle_venta', models.ManyToManyField(to='ventas.DetalleVenta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
