# Generated by Django 3.2.6 on 2021-11-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='id_detalle_venta',
        ),
        migrations.AddField(
            model_name='venta',
            name='id_detalle_venta',
            field=models.ManyToManyField(to='ventas.DetalleVenta'),
        ),
    ]
