# Generated by Django 3.2.6 on 2021-11-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20211103_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tipo_factura',
            field=models.CharField(choices=[('CON', 'CONTADO'), ('CRE', 'CREDITO')], default='CON', max_length=3),
        ),
    ]
