# Generated by Django 3.2.6 on 2021-10-19 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20211017_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='cantidad',
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='venta',
            name='hora',
            field=models.TimeField(default='14:09:51'),
        ),
    ]
