# Generated by Django 3.2.6 on 2021-12-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_venta_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='numero_factura_asignado',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
