# Generated by Django 3.2.6 on 2021-12-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_venta_numero_factura_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='total_nota_credito',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
