# Generated by Django 3.2.6 on 2021-10-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_venta_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='hora',
            field=models.TimeField(default='14:14:53'),
        ),
    ]
