# Generated by Django 3.2.6 on 2021-12-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_venta_total_nota_credito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
