# Generated by Django 3.2.6 on 2021-12-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_auto_20211202_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='hora',
            field=models.TimeField(default='14:31:44'),
        ),
    ]
