# Generated by Django 3.2.6 on 2021-10-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_alter_venta_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venta',
            name='hora',
            field=models.TimeField(default='16:58:41'),
        ),
    ]
