# Generated by Django 3.2.6 on 2021-10-21 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_auto_20211021_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('H', 'Historico')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='venta',
            name='hora',
            field=models.TimeField(default='18:07:23'),
        ),
    ]
