# Generated by Django 3.2.6 on 2021-10-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_auto_20211021_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='estado',
            field=models.CharField(choices=[('A', 'ACTIVO'), ('H', 'HISTORICO')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('A', 'ACTIVO'), ('H', 'HISTORICO')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='venta',
            name='hora',
            field=models.TimeField(default='18:37:16'),
        ),
    ]
