# Generated by Django 3.2.6 on 2021-10-21 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_auto_20211021_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='venta',
            name='hora',
            field=models.TimeField(default='22:25:50'),
        ),
    ]
