# Generated by Django 3.2.6 on 2021-11-16 18:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articulos', '0013_auto_20211102_2303'),
        ('proveedores', '0005_alter_proveedor_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_orden_compra', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_entrada', models.DateField(default=datetime.date.today)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio', models.IntegerField()),
                ('iva', models.IntegerField(choices=[(10, 'IVA 10%'), (5, 'IVA 5%')])),
                ('sub_total', models.IntegerField(default=0)),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.articulo')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
        ),
    ]
