# Generated by Django 3.2.6 on 2021-08-12 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('codigo', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id_articulo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=32)),
                ('porc_iva', models.PositiveIntegerField()),
                ('porc_comision', models.IntegerField()),
                ('stock_actual', models.PositiveBigIntegerField()),
                ('stock_minimo', models.IntegerField()),
                ('ultima_compra', models.DateField()),
                ('unidad_medida', models.CharField(max_length=4)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=32)),
                ('precio_mayorista', models.DecimalField(decimal_places=4, max_digits=32)),
                ('precio_especial', models.DecimalField(decimal_places=4, max_digits=32)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.marca')),
            ],
        ),
    ]
