# Generated by Django 3.2.6 on 2021-08-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='id_articulo',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
