# Generated by Django 3.2.6 on 2021-10-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_alter_articulo_id_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='codigo_barras',
            field=models.CharField(default=131, max_length=15),
            preserve_default=False,
        ),
    ]
