# Generated by Django 3.2.6 on 2021-10-21 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_rename_codigo_barras_articulo_codigo_barra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='codigo_barra',
            new_name='codigo_barras',
        ),
    ]
