# Generated by Django 3.2.6 on 2021-10-21 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0005_rename_codigo_barra_articulo_codigo_barras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='codigo',
            new_name='id_marca',
        ),
        migrations.RenameField(
            model_name='marca',
            old_name='codigo',
            new_name='id_marca',
        ),
    ]
