# Generated by Django 3.2.6 on 2021-10-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0006_auto_20211021_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='unidad_medida',
            field=models.CharField(choices=[('Kiligramos', 'kILOGRAMOS'), ('Caja', 'CAJA'), ('Unidad', 'UNIDAD')], max_length=10),
        ),
    ]
