# Generated by Django 3.2.6 on 2021-10-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0007_alter_articulo_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='unidad_medida',
            field=models.CharField(choices=[('Kiligramos', 'KILOGRAMOS'), ('Caja', 'CAJA'), ('Unidad', 'UNIDAD'), ('Centimetros Cúbicos', 'CENTIMETROS CUBICOS')], max_length=20),
        ),
    ]
