# Generated by Django 3.2.6 on 2021-10-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0008_alter_articulo_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='unidad_medida',
            field=models.CharField(choices=[('KG', 'KILOGRAMOS'), ('CJ', 'CAJA'), ('UN', 'UNIDAD'), ('CC', 'CENTIMETROS CÚBICOS')], max_length=20),
        ),
    ]
