# Generated by Django 3.2.6 on 2021-11-02 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0012_auto_20211021_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='marca',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
