# Generated by Django 3.2.6 on 2021-12-05 17:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articulos', '0013_auto_20211102_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteStock',
            fields=[
                ('estado', models.CharField(choices=[('A', 'ACTIVO'), ('H', 'HISTORICO')], default='A', max_length=1)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('id_ajuste_stock', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_ajuste', models.CharField(choices=[('A', 'ALTA'), ('B', 'BAJA')], max_length=1)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('motivo_ajuste', models.CharField(max_length=200)),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.articulo')),
                ('id_ususario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
