# Generated by Django 3.2.6 on 2021-12-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0014_ajustestock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ajustestock',
            old_name='id_ususario',
            new_name='id_usuario',
        ),
    ]
