# Generated by Django 3.2.6 on 2021-09-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id_configuracion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('comision_x_venta', models.IntegerField()),
                ('estado_activo', models.BooleanField(default=True)),
                ('ruc_empresa', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('pagina_web', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
