# Generated by Django 3.2.6 on 2021-11-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracion',
            old_name='id_configuracion',
            new_name='id_impresora',
        ),
        migrations.RenameField(
            model_name='configuracion',
            old_name='direccion',
            new_name='nombre_impresora',
        ),
        migrations.RenameField(
            model_name='configuracion',
            old_name='comision_x_venta',
            new_name='numero_facrura',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='estado_activo',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='nombre_empresa',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='pagina_web',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='ruc_empresa',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='telefono',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='coordenada_x',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracion',
            name='coordenada_y',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracion',
            name='numeracion_fija_factura',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
