# Generated by Django 3.2.6 on 2021-11-28 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_auto_20211128_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracion',
            old_name='numero_facrura',
            new_name='numero_factura',
        ),
    ]
