# Generated by Django 3.2.6 on 2021-11-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_rename_numero_facrura_configuracion_numero_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='numero_final',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
