# Generated by Django 3.2.6 on 2021-09-18 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_modulo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=30)),
                ('usuario', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PermisoModuloRol',
            fields=[
                ('id_permiso_modulo_rol', models.AutoField(primary_key=True, serialize=False)),
                ('modulo', models.ManyToManyField(to='roles.Modulo')),
                ('permiso', models.ManyToManyField(to='roles.Permiso')),
                ('rol', models.ManyToManyField(to='roles.Rol')),
            ],
        ),
    ]
