# Generated by Django 3.2.6 on 2021-09-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='modulo',
            field=models.ManyToManyField(to='roles.Modulo'),
        ),
        migrations.AddField(
            model_name='rol',
            name='permiso',
            field=models.ManyToManyField(to='roles.Permiso'),
        ),
        migrations.DeleteModel(
            name='PermisoModuloRol',
        ),
    ]
