# Generated by Django 3.2.6 on 2021-10-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_auto_20210921_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre_rol',
            field=models.CharField(max_length=50),
        ),
    ]
