# Generated by Django 3.2.6 on 2021-12-01 13:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0004_venta_id_usuario'),
        ('articulos', '0013_auto_20211102_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleNotaCredito',
            fields=[
                ('estado', models.CharField(choices=[('A', 'ACTIVO'), ('H', 'HISTORICO')], default='A', max_length=1)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('id_detalle_nota_credito', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.articulo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotaCreditoCliente',
            fields=[
                ('estado', models.CharField(choices=[('A', 'ACTIVO'), ('H', 'HISTORICO')], default='A', max_length=1)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('id_nota_credito_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('monto_total', models.PositiveIntegerField(default=0)),
                ('id_detalle_nota_credito', models.ManyToManyField(to='nota_credito.DetalleNotaCredito')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
