# Generated by Django 3.2.6 on 2021-12-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_credito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallenotacredito',
            name='id_detalle_nota_credito',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notacreditocliente',
            name='id_nota_credito_cliente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
