# Generated by Django 3.2.6 on 2021-12-01 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nota_credito', '0002_auto_20211201_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notacreditocliente',
            name='id_detalle_nota_credito',
        ),
        migrations.AddField(
            model_name='notacreditocliente',
            name='id_detalle_nota_credito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nota_credito.detallenotacredito'),
            preserve_default=False,
        ),
    ]
