# Generated by Django 3.2.6 on 2021-12-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_venta_id_usuario'),
        ('nota_credito', '0003_auto_20211201_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notacreditocliente',
            name='id_venta',
        ),
        migrations.AddField(
            model_name='notacreditocliente',
            name='id_venta',
            field=models.ManyToManyField(to='ventas.Venta'),
        ),
    ]
