# Generated by Django 3.2.6 on 2021-12-01 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_venta_id_usuario'),
        ('nota_credito', '0004_auto_20211201_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notacreditocliente',
            name='id_venta',
        ),
        migrations.AddField(
            model_name='notacreditocliente',
            name='id_venta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ventas.venta'),
            preserve_default=False,
        ),
    ]
