# Generated by Django 3.2.6 on 2021-12-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_credito', '0005_auto_20211201_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notacreditocliente',
            name='id_detalle_nota_credito',
        ),
        migrations.AddField(
            model_name='notacreditocliente',
            name='id_detalle_nota_credito',
            field=models.ManyToManyField(to='nota_credito.DetalleNotaCredito'),
        ),
    ]
