# Generated by Django 3.2.6 on 2021-12-01 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_venta_id_usuario'),
        ('nota_credito', '0006_auto_20211201_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallenotacredito',
            name='id_venta',
            field=models.ForeignKey(default=249, on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.venta'),
            preserve_default=False,
        ),
    ]
