# Generated by Django 3.2.6 on 2021-12-03 14:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_auto_20211203_1431'),
        ('articulos', '0013_auto_20211102_2303'),
        ('nota_credito', '0007_detallenotacredito_id_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCreditoProveedor',
            fields=[
                ('estado', models.CharField(choices=[('A', 'ACTIVO'), ('H', 'HISTORICO')], default='A', max_length=1)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('id_nota_credito_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('monto_total', models.PositiveIntegerField(default=0)),
                ('id_detalle_nota_credito_proveedor', models.ManyToManyField(to='nota_credito.DetalleNotaCredito')),
                ('id_factura_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.facturacompra')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleNotaCreditoProveedor',
            fields=[
                ('estado', models.CharField(choices=[('A', 'ACTIVO'), ('H', 'HISTORICO')], default='A', max_length=1)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('id_detalle_nota_credito_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('costo_unitario', models.PositiveIntegerField(default=0)),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.articulo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
