# Generated by Django 3.2.6 on 2021-12-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_credito', '0008_detallenotacreditoproveedor_notacreditoproveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacreditoproveedor',
            name='id_detalle_nota_credito_proveedor',
            field=models.ManyToManyField(to='nota_credito.DetalleNotaCreditoProveedor'),
        ),
    ]
