# Generated by Django 3.2.6 on 2021-12-02 20:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articulos', '0013_auto_20211102_2303'),
        ('personas', '0004_alter_persona_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFacturaCompra',
            fields=[
                ('estado', models.CharField(choices=[('A', 'ACTIVO'), ('H', 'HISTORICO')], default='A', max_length=1)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('id_detalle_factura_compra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('costo_unitario', models.PositiveIntegerField(default=0)),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.articulo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('estado', models.CharField(choices=[('A', 'ACTIVO'), ('H', 'HISTORICO')], default='A', max_length=1)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('timbrado', models.IntegerField(max_length=10)),
                ('cantidad_facturas', models.IntegerField(max_length=3)),
                ('tipo_factura', models.CharField(choices=[('CON', 'Contado'), ('CRE', 'Credito')], default='CON', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('estado', models.CharField(choices=[('A', 'ACTIVO'), ('H', 'HISTORICO')], default='A', max_length=1)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('id_factura_compra', models.AutoField(primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(max_length=100)),
                ('total', models.PositiveIntegerField(default=0)),
                ('id_detalle_factura_compra', models.ManyToManyField(to='facturas.DetalleFacturaCompra')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.persona')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
