# Generated by Django 3.2.6 on 2021-12-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cantidad_facturas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='timbrado',
            field=models.IntegerField(),
        ),
    ]
