# Generated by Django 3.2.6 on 2021-12-03 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_alter_proveedor_fecha_creacion'),
        ('facturas', '0002_auto_20211203_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompra',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor'),
        ),
    ]
