# Generated by Django 3.2.6 on 2021-12-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_alter_facturacompra_id_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='total_nota_credito',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
