# Generated by Django 3.2.6 on 2021-11-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='id_orden_compra',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
