# Generated by Django 3.2.6 on 2021-10-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='propietario',
            field=models.CharField(default='Prueba', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(default='80000000-0', max_length=50),
            preserve_default=False,
        ),
    ]
