# Generated by Django 3.2.6 on 2021-09-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_persona', models.CharField(choices=[('F', 'Fisica'), ('J', 'Juridica')], default='F', max_length=1)),
                ('nombre_apellido', models.CharField(max_length=100)),
                ('propietario', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=40)),
                ('ruc', models.CharField(blank=True, max_length=50, null=True)),
                ('cedula', models.CharField(blank=True, max_length=50, null=True)),
                ('correo_electronico', models.CharField(blank=True, max_length=50, null=True)),
                ('es_cliente', models.CharField(choices=[('V', 'Verdadero'), ('F', 'Falso')], default='V', max_length=1)),
                ('es_proveedor', models.CharField(choices=[('V', 'Verdadero'), ('F', 'Falso')], default='F', max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('estado_activo', models.CharField(choices=[('V', 'Verdadero'), ('F', 'Falso')], default='V', max_length=1)),
            ],
        ),
    ]
